- name: apache-start
  service: name=apache2 start=started

- name: apache-restart
  service: name=apache2 state=restarted

- name: apache-reload
  service: name=apache2 state=reloaded

- name: nginx-start
  service: name=nginx start=started

- name: nginx-restart
  service: name=nginx state=restarted

- name: nginx-reload
  service: name=nginx state=reloaded

